In [3]:
import numpy as np
import pandas as pd

### Importando a matriz de dados

In [4]:
matrix = np.loadtxt('resources/teste.txt', delimiter=' ')
df = pd.DataFrame(matrix,index=matrix[:,-1].astype(int))
array = df[1].to_numpy()
array = np.ma.masked_equal(array,0)
array = array.compressed()

array


array([0.000387, 0.007009, 0.001467, 0.020309, 0.010393, 0.015306,
       0.007171, 0.008899, 0.002046, 0.011831, 0.014894, 0.021614,
       0.004801, 0.016355, 0.026831, 0.010712, 0.0425  , 0.018707,
       0.001391, 0.008084, 0.021591, 0.01789 , 0.02077 , 0.003817,
       0.027147, 0.004054, 0.001602, 0.001424, 0.015244, 0.010972,
       0.03861 , 0.027461, 0.032305, 0.00542 , 0.022472, 0.005487,
       0.019444, 0.034022, 0.010232, 0.005025, 0.01162 , 0.007681,
       0.021583, 0.023277, 0.035769, 0.015914, 0.000685, 0.003998,
       0.022951, 0.006014, 0.024703, 0.006245, 0.019391, 0.011429,
       0.015205, 0.009919, 0.026436, 0.002346, 0.017825, 0.016896,
       0.012486, 0.023721, 0.038285, 0.006829, 0.025373, 0.018445,
       0.019388, 0.009295, 0.002647, 0.014725, 0.025994, 0.018824,
       0.006459, 0.002309, 0.009977, 0.019344, 0.011905, 0.016588,
       0.012646, 0.00067 , 0.010973, 0.026059, 0.009681, 0.016023,
       0.007233, 0.008431, 0.013575, 0.003848, 0.004556, 0.001

In [5]:
from scipy.spatial import distance

def f(s, range=(0,1)):
    return ((s - s.min())/(s.max() - s.min())*(
        (range[1] - range[0]) + range[0]
    ))

norm_df = df.apply(f , axis=1).copy()

norm_df.iloc[0].values

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.        , 0.2366968 , 0.09468008,
       0.09468008, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.22248354, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.35211392, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.28403684, 0.28403684, 0.09468008,
       0.        , 0.        , 0.        , 0.70304852, 0.        ,
       0.        , 0.        , 0.        , 0.08450584, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.43661977, 0.09468008, 0.28403684, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.52506237, 0.        , 0.        , 0.        , 0.        ,
       0.25352093, 0.        , 0.        , 0.        , 0.     

In [18]:
from scipy import stats

def z_score(a):
    return (a - a.mean())/a.std()

a = np.array([73600,54000,16000])

print(stats.zscore(a))

df_zscore = df.apply(z_score , axis=1).copy()

df_zscore



[ 1.07618215  0.25649937 -1.33268153]


0         1         2         3         4         5         6    \
0  -0.088805 -0.307547 -0.350805 -0.133858 -0.406708 -0.313333 -0.282442   
0  -0.088805 -0.307547 -0.350805 -0.133858 -0.406708 -0.313333 -0.282442   
0  -0.088805 -0.307547 -0.350805 -0.133858 -0.406708 -0.313333 -0.282442   
0  -0.088805 -0.307547 -0.350805 -0.133858 -0.406708 -0.313333 -0.282442   
0  -0.088805 -0.307547 -0.350805 -0.133858 -0.406708 -0.092790 -0.282442   
..       ...       ...       ...       ...       ...       ...       ...   
9  -0.088805  3.302372 -0.350805  2.745744  0.166401 -0.313333  0.517735   
9  -0.088805 -0.307547 -0.350805 -0.133858  0.431377 -0.313333 -0.282442   
9  -0.088805 -0.307547 -0.350805 -0.133858  0.730063 -0.313333 -0.282442   
9  -0.088805 -0.307547 -0.350805 -0.133858  1.112087 -0.313333 -0.282442   
9  -0.088805 -0.307547 -0.350805 -0.133858  1.198159 -0.313333 -0.282442   

        7         8         9    ...       123       124       125       126  \
0  -0.15561 -0.465842 -0.181014  ... -0.186174 -0.440264 -0.254022 -0.432381   
0  -0.15561 -0.465842 -0.181014  ... -0.186174 -0.440264 -0.254022 -0.432381   
0  -0.15561 -0.465842 -0.181014  ... -0.186174 -0.440264 -0.254022 -0.432381   
0  -0.15561 -0.465842 -0.181014  ... -0.186174 -0.440264 -0.254022  0.755399   
0  -0.15561 -0.353038 -0.181014  ... -0.186174 -0.440264 -0.254022 -0.432381   
..      ...       ...       ...  ...       ...       ...       ...       ...   
9  -0.15561 -0.465842 -0.181014  ... -0.186174 -0.440264 -0.254022 -0.432381   
9  -0.15561 -0.414742 -0.181014  ... -0.186174 -0.440264 -0.254022 -0.432381   
9  -0.15561 -0.465842 -0.181014  ... -0.102516 -0.440264 -0.254022 -0.432381   
9  -0.15561 -0.465842 -0.181014  ...  0.074469  0.649532 -0.254022 -0.432381   
9  -0.15561 -0.465842 -0.181014  ...  0.068584  0.092344 -0.254022 -0.432381   

         127       128       129       130       131       132  
0  -0.005261  1.435662  1.893080 -0.318049  0.438437 -1.565915  
0   0.632330  1.388257  0.787913  0.500733  0.405438 -1.565915  
0  -0.005261  1.435662  2.272984 -0.318049  0.731864 -1.565915  
0   0.274958  1.365193  1.451576  0.655641  1.007320 -1.565915  
0   0.418065  1.478635  1.164562 -0.318049  0.537995 -1.565915  
..       ...       ...       ...       ...       ...       ...  
9  -0.615143 -0.360713 -0.766225 -0.318049 -1.162759  1.565915  
9  -0.615143 -0.857268 -0.766225 -0.318049 -1.348748  1.565915  
9   0.035401  0.774840 -0.766225 -0.318049 -0.482015  1.565915  
9   0.229313  1.427661 -0.555826 -0.318049  0.137885  1.565915  
9   0.540424  1.368987 -0.766225 -0.318049  0.086414  1.565915  

[1000 rows x 133 columns]

In [ ]:
from scipy.spatial import distance

distance.euclidean(norm_df.iloc[0].values,norm_df.iloc[1].values)

distance.cityblock([1,2],[0,3])

In [ ]:
a = [73.600,12.000,98.000]

arr = np.array(a)

f(arr)

In [ ]:
def min_max_cru(attribute_list, value):
    return (value - min(attribute_list))/(max(attribute_list) - min(attribute_list))

min_max(df.iloc[0].values, df.iloc[2].values[12])
    


In [ ]:
a = [1,2,3,4,5,6,7,8,9,0]

a = np.array(a)


matrix = np.loadtxt('resources/teste.txt', delimiter=' ')
df = pd.DataFrame(matrix,index=matrix[:,-1].astype(int))


df.drop(df.columns[len(df.columns)-1], axis=1, inplace=True)


# df.index.get_loc(df[0][1])


# for index, row in df.iterrows():
#     print(index)

In [ ]:
    from scipy.spatial import distance
    from statistics import mode 

    def min_max(a):
        return (a - a.min())/(a.max() - a.min())
    
    training_matrix = np.loadtxt('resources/treinamento.txt', delimiter=' ')
    test_matrix = np.loadtxt('resources/teste.txt', delimiter=' ')

    training_df = pd.DataFrame(training_matrix,index=training_matrix[:,-1].astype(int))
    training_df.drop(training_df.columns[len(training_df.columns)-1], axis=1, inplace=True)
    
    test_df = pd.DataFrame(test_matrix,index=test_matrix[:,-1].astype(int))
    test_df.drop(test_df.columns[len(test_df.columns)-1], axis=1, inplace=True)

    
    training_norm_df = training_df.apply(min_max , axis=1).copy()
    
    test_norm_df = test_df.apply(min_max , axis=1).copy()

    objeto = test_norm_df.iloc[0].values

    distances = []

    minvalues = [[float('inf'),None] for _ in range(3)]

    for _class, row in training_norm_df.iterrows():

        distancia = distance.euclidean(objeto,row.values)

        minvalues.sort(key=lambda dist: dist[0], reverse=True)
        for value in minvalues:
            if distancia < value[0]:
                value[0] = distancia
                value[1] = _class
                break
            

    minvalues = [item[1] for item in minvalues]

    minvalues


    

In [ ]:
minvalues = [[float('inf'),None] for _ in range(3)]
minvalues