In [3]:
import numpy as np
import pandas as pd

### Importando a matriz de dados

In [4]:
matrix = np.loadtxt('resources/teste.txt', delimiter=' ')
df = pd.DataFrame(matrix,index=matrix[:,-1].astype(int))
array = df[1].to_numpy()
array = np.ma.masked_equal(array,0)
array = array.compressed()

array


array([0.000387, 0.007009, 0.001467, 0.020309, 0.010393, 0.015306,
       0.007171, 0.008899, 0.002046, 0.011831, 0.014894, 0.021614,
       0.004801, 0.016355, 0.026831, 0.010712, 0.0425  , 0.018707,
       0.001391, 0.008084, 0.021591, 0.01789 , 0.02077 , 0.003817,
       0.027147, 0.004054, 0.001602, 0.001424, 0.015244, 0.010972,
       0.03861 , 0.027461, 0.032305, 0.00542 , 0.022472, 0.005487,
       0.019444, 0.034022, 0.010232, 0.005025, 0.01162 , 0.007681,
       0.021583, 0.023277, 0.035769, 0.015914, 0.000685, 0.003998,
       0.022951, 0.006014, 0.024703, 0.006245, 0.019391, 0.011429,
       0.015205, 0.009919, 0.026436, 0.002346, 0.017825, 0.016896,
       0.012486, 0.023721, 0.038285, 0.006829, 0.025373, 0.018445,
       0.019388, 0.009295, 0.002647, 0.014725, 0.025994, 0.018824,
       0.006459, 0.002309, 0.009977, 0.019344, 0.011905, 0.016588,
       0.012646, 0.00067 , 0.010973, 0.026059, 0.009681, 0.016023,
       0.007233, 0.008431, 0.013575, 0.003848, 0.004556, 0.001

In [5]:
from scipy.spatial import distance

def f(s, range=(0,1)):
    return ((s - s.min())/(s.max() - s.min())*(
        (range[1] - range[0]) + range[0]
    ))

norm_df = df.apply(f , axis=1).copy()

norm_df.iloc[0].values

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.        , 0.2366968 , 0.09468008,
       0.09468008, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.22248354, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.35211392, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.28403684, 0.28403684, 0.09468008,
       0.        , 0.        , 0.        , 0.70304852, 0.        ,
       0.        , 0.        , 0.        , 0.08450584, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.43661977, 0.09468008, 0.28403684, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.52506237, 0.        , 0.        , 0.        , 0.        ,
       0.25352093, 0.        , 0.        , 0.        , 0.     

In [19]:
from scipy import stats

def z_score(a):
    return (a - a.mean())/a.std()

a = np.array([73600,54000,16000])

print(stats.zscore(a))

df_zscore = df.apply(z_score , axis=1).copy()

df_zscore



[ 1.07618215  0.25649937 -1.33268153]


0         1         2         3         4         5         6    \
0  -0.436642 -0.436642 -0.436642 -0.436642 -0.436642 -0.436642 -0.436642   
0  -0.469746 -0.469746 -0.469746 -0.469746 -0.469746 -0.469746 -0.469746   
0  -0.446475 -0.446475 -0.446475 -0.446475 -0.446475 -0.446475 -0.446475   
0  -0.431963 -0.431963 -0.431963 -0.431963 -0.431963 -0.431963 -0.431963   
0  -0.449777 -0.449777 -0.449777 -0.449777 -0.449777 -0.394842 -0.449777   
..       ...       ...       ...       ...       ...       ...       ...   
9  -0.115690 -0.085040 -0.115690 -0.102919 -0.100365 -0.115690 -0.108028   
9  -0.115646 -0.115646 -0.115646 -0.115646 -0.093244 -0.115646 -0.115646   
9  -0.115681 -0.115681 -0.115681 -0.115681 -0.085286 -0.115681 -0.115681   
9  -0.115680 -0.115680 -0.115680 -0.115680 -0.075070 -0.115680 -0.115680   
9  -0.115685 -0.115685 -0.115685 -0.115685 -0.072772 -0.115685 -0.115685   

         7         8         9    ...       123       124       125       126  \
0  -0.436642 -0.436642 -0.436642  ... -0.436642 -0.436642 -0.436642 -0.436642   
0  -0.469746 -0.469746 -0.469746  ... -0.469746 -0.469746 -0.469746 -0.469746   
0  -0.446475 -0.446475 -0.446475  ... -0.446475 -0.446475 -0.446475 -0.446475   
0  -0.431963 -0.431963 -0.431963  ... -0.431963 -0.431963 -0.431963 -0.173166   
0  -0.449777 -0.394842 -0.449777  ... -0.449777 -0.449777 -0.449777 -0.449777   
..       ...       ...       ...  ...       ...       ...       ...       ...   
9  -0.115690 -0.115690 -0.115690  ... -0.115690 -0.115690 -0.115690 -0.115690   
9  -0.115646 -0.114047 -0.115646  ... -0.115646 -0.115646 -0.115646 -0.115646   
9  -0.115681 -0.115681 -0.115681  ... -0.106184 -0.115681 -0.115681 -0.115681   
9  -0.115680 -0.115680 -0.115680  ... -0.086092 -0.095954 -0.115680 -0.115680   
9  -0.115685 -0.115685 -0.115685  ... -0.086764 -0.106044 -0.115685 -0.115685   

         127       128       129       130       131        132  
0   0.101079  0.907641  1.445362 -0.436642  2.494825  -0.436642  
0   0.713511  0.950171  0.713511 -0.233086  2.626491  -0.469746  
0   0.103355  0.928081  1.752827 -0.446475  3.036787  -0.446475  
0   0.344411  0.861988  1.120766 -0.173166  3.379282  -0.431963  
0   0.488585  0.957755  0.957755 -0.449777  2.735915  -0.449777  
..       ...       ...       ...       ...       ...        ...  
9  -0.115690 -0.087966 -0.115690 -0.115690 -0.093234  11.424417  
9  -0.115646 -0.104876 -0.115646 -0.115646 -0.113138  11.420063  
9  -0.077692 -0.049200 -0.115681 -0.115681 -0.020226  11.423514  
9  -0.066367 -0.026917 -0.105818 -0.115680  0.046249  11.423371  
9  -0.048201 -0.028921 -0.115685 -0.115685  0.040731  11.423856  

[1000 rows x 133 columns]

In [ ]:
from scipy.spatial import distance

distance.euclidean(norm_df.iloc[0].values,norm_df.iloc[1].values)

distance.cityblock([1,2],[0,3])

In [ ]:
a = [73.600,12.000,98.000]

arr = np.array(a)

f(arr)

In [ ]:
def min_max_cru(attribute_list, value):
    return (value - min(attribute_list))/(max(attribute_list) - min(attribute_list))

min_max(df.iloc[0].values, df.iloc[2].values[12])
    


In [ ]:
a = [1,2,3,4,5,6,7,8,9,0]

a = np.array(a)


matrix = np.loadtxt('resources/teste.txt', delimiter=' ')
df = pd.DataFrame(matrix,index=matrix[:,-1].astype(int))


df.drop(df.columns[len(df.columns)-1], axis=1, inplace=True)


# df.index.get_loc(df[0][1])


# for index, row in df.iterrows():
#     print(index)

In [ ]:
    from scipy.spatial import distance
    from statistics import mode 

    def min_max(a):
        return (a - a.min())/(a.max() - a.min())
    
    training_matrix = np.loadtxt('resources/treinamento.txt', delimiter=' ')
    test_matrix = np.loadtxt('resources/teste.txt', delimiter=' ')

    training_df = pd.DataFrame(training_matrix,index=training_matrix[:,-1].astype(int))
    training_df.drop(training_df.columns[len(training_df.columns)-1], axis=1, inplace=True)
    
    test_df = pd.DataFrame(test_matrix,index=test_matrix[:,-1].astype(int))
    test_df.drop(test_df.columns[len(test_df.columns)-1], axis=1, inplace=True)

    
    training_norm_df = training_df.apply(min_max , axis=1).copy()
    
    test_norm_df = test_df.apply(min_max , axis=1).copy()

    objeto = test_norm_df.iloc[0].values

    distances = []

    minvalues = [[float('inf'),None] for _ in range(3)]

    for _class, row in training_norm_df.iterrows():

        distancia = distance.euclidean(objeto,row.values)

        minvalues.sort(key=lambda dist: dist[0], reverse=True)
        for value in minvalues:
            if distancia < value[0]:
                value[0] = distancia
                value[1] = _class
                break
            

    minvalues = [item[1] for item in minvalues]

    minvalues


    

In [ ]:
minvalues = [[float('inf'),None] for _ in range(3)]
minvalues